# Generated by Django 4.2.6 on 2024-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='images',
            field=models.ImageField(upload_to='product_image'),
        ),
    ]
