# Generated by Django 4.2.6 on 2024-08-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_productmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='images',
            field=models.ImageField(upload_to='image'),
        ),
    ]
