# Generated by Django 4.2.6 on 2024-08-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_productmodel_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='images',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='images',
            field=models.ManyToManyField(blank=True, to='sale.productimage'),
        ),
    ]
